name: felpus
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: 4.6.6
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.7.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  intl_phone_field: ^3.2.0
  socket_io_client: ^2.0.3+1
  loading_animation_widget: ^1.2.1
  fluttertoast: ^8.2.6
  connectivity_plus: ^6.0.4
  font_awesome_flutter: ^10.7.0
  flutter_phone_direct_caller: ^2.1.1
  google_mobile_ads: ^5.1.0
  flutter_image_compress: ^2.3.0
  image: ^4.2.0
  icons_launcher: ^2.1.7
  url_launcher: ^6.3.0


icons_launcher:
  image_path: 'assets/images/launcherIcon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/.env
#    - assets/images/tratamiento_fracturas.png
#    - assets/icons/svgIcon/

